resource "aws_customerprofiles_profile" "tf-sample-customerprofiles-profile" {
  account_number         = ""
  additional_information = ""
  attributes             = {}
  birth_date             = ""
  business_email_address = ""
  business_name          = ""
  business_phone_number  = ""
  domain_name            = ""
  email_address          = ""
  first_name             = ""
  gender_string          = ""
  home_phone_number      = ""
  last_name              = ""
  middle_name            = ""
  mobile_phone_number    = ""
  party_type_string      = ""
  personal_email_address = ""
  phone_number           = ""
  region                 = ""
  
  address {
    address_1   = ""
    address_2   = ""
    address_3   = ""
    address_4   = ""
    city        = ""
    country     = ""
    county      = ""
    postal_code = ""
    province    = ""
    state       = ""
  }
  billing_address {
    address_1   = ""
    address_2   = ""
    address_3   = ""
    address_4   = ""
    city        = ""
    country     = ""
    county      = ""
    postal_code = ""
    province    = ""
    state       = ""
  }
  mailing_address {
    address_1   = ""
    address_2   = ""
    address_3   = ""
    address_4   = ""
    city        = ""
    country     = ""
    county      = ""
    postal_code = ""
    province    = ""
    state       = ""
  }
  shipping_address {
    address_1   = ""
    address_2   = ""
    address_3   = ""
    address_4   = ""
    city        = ""
    country     = ""
    county      = ""
    postal_code = ""
    province    = ""
    state       = ""
  }
}