resource "aws_network_acl_rule" "sample-network-acl-rule" {
  cidr_block      = ""
  egress          = ""
  from_port       = ""
  icmp_code       = ""
  icmp_type       = ""
  id              = ""
  ipv6_cidr_block = ""
  network_acl_id  = ""
  protocol        = ""
  region          = ""
  rule_action     = ""
  rule_number     = ""
  to_port         = ""
}