resource "aws_odb_cloud_exadata_infrastructure" "sample-odb-cloud-exadata-infrastructure" {
  activated_storage_count          = ""
  additional_storage_count         = ""
  availability_zone                = ""
  availability_zone_id             = ""
  available_storage_size_in_gbs    = ""
  compute_count                    = ""
  compute_model                    = ""
  cpu_count                        = ""
  created_at                       = ""
  customer_contacts_to_send_to_oci = []
  data_storage_size_in_tbs         = ""
  database_server_type             = ""
  db_node_storage_size_in_gbs      = ""
  db_server_version                = ""
  display_name                     = ""
  id                               = ""
  last_maintenance_run_id          = ""
  max_cpu_count                    = ""
  max_data_storage_in_tbs          = ""
  max_db_node_storage_size_in_gbs  = ""
  max_memory_in_gbs                = ""
  memory_size_in_gbs               = ""
  monthly_db_server_version        = ""
  monthly_storage_server_version   = ""
  next_maintenance_run_id          = ""
  oci_resource_anchor_name         = ""
  oci_url                          = ""
  ocid                             = ""
  percent_progress                 = ""
  region                           = ""
  shape                            = ""
  status                           = ""
  status_reason                    = ""
  storage_count                    = ""
  storage_server_type              = ""
  storage_server_version           = ""
  total_storage_size_in_gbs        = ""
  
  maintenance_window {}
  
  tags = {}
}