resource "oci_oce_oce_instance" "tf-sample-oce-oce-instance" {
  admin_email              = ""
  compartment_id           = ""
  description              = ""
  dr_region                = ""
  idcs_access_token        = ""
  instance_access_type     = ""
  instance_license_type    = ""
  instance_usage_type      = ""
  name                     = ""
  object_storage_namespace = ""
  tenancy_id               = ""
  tenancy_name             = ""
  upgrade_schedule         = ""
  waf_primary_domain       = ""
}