resource "alicloud_oss_bucket_object" "tf-sample-oss-bucket-object" {
  acl                           = ""
  bucket                        = ""
  cache_control                 = ""
  content                       = ""
  content_disposition           = ""
  content_encoding              = ""
  content_md5                   = ""
  content_type                  = ""
  expires                       = ""
  key                           = ""
  kms_key_id                    = ""
  object_worm_mode              = ""
  object_worm_retain_until_date = ""
  server_side_encryption        = ""
  source                        = ""
}