resource "oci_golden_gate_database_registration" "tf-sample-golden-gate-database-registration" {
  alias_name            = ""
  compartment_id        = ""
  connection_string     = ""
  database_id           = ""
  description           = ""
  display_name          = ""
  fqdn                  = ""
  ip_address            = ""
  key_id                = ""
  password              = ""
  secret_compartment_id = ""
  session_mode          = ""
  subnet_id             = ""
  username              = ""
  vault_id              = ""
  wallet                = ""
}