resource "oci_database_migration_connection" "tf-sample-database-migration-connection" {
  compartment_id       = ""
  connection_string    = ""
  connection_type      = ""
  database_id          = ""
  database_name        = ""
  db_system_id         = ""
  description          = ""
  display_name         = ""
  host                 = ""
  key_id               = ""
  password             = ""
  port                 = 0
  replication_password = ""
  replication_username = ""
  security_protocol    = ""
  ssh_host             = ""
  ssh_key              = ""
  ssh_sudo_location    = ""
  ssh_user             = ""
  ssl_ca               = ""
  ssl_cert             = ""
  ssl_crl              = ""
  ssl_key              = ""
  ssl_mode             = ""
  subnet_id            = ""
  technology_type      = ""
  username             = ""
  vault_id             = ""
  wallet               = ""
  
  additional_attributes {
    name  = ""
    value = ""
  }
}