resource "aws_rds_cluster_instance" "sample-rds-cluster-instance" {
  apply_immediately                     = ""
  auto_minor_version_upgrade            = ""
  availability_zone                     = ""
  ca_cert_identifier                    = ""
  cluster_identifier                    = ""
  copy_tags_to_snapshot                 = ""
  custom_iam_instance_profile           = ""
  db_parameter_group_name               = ""
  db_subnet_group_name                  = ""
  dbi_resource_id                       = ""
  endpoint                              = ""
  engine                                = ""
  engine_version                        = ""
  engine_version_actual                 = ""
  force_destroy                         = ""
  id                                    = ""
  identifier                            = ""
  identifier_prefix                     = ""
  instance_class                        = ""
  kms_key_id                            = ""
  monitoring_interval                   = ""
  monitoring_role_arn                   = ""
  network_type                          = ""
  performance_insights_enabled          = ""
  performance_insights_kms_key_id       = ""
  performance_insights_retention_period = ""
  port                                  = ""
  preferred_backup_window               = ""
  preferred_maintenance_window          = ""
  promotion_tier                        = ""
  publicly_accessible                   = ""
  region                                = ""
  storage_encrypted                     = ""
  writer                                = ""
  
  tags = {}
}