resource "aws_odb_cloud_autonomous_vm_cluster" "tf-sample-odb-cloud-autonomous-vm-cluster" {
  autonomous_data_storage_percentage               = ""
  autonomous_data_storage_size_in_tbs              = ""
  available_autonomous_data_storage_size_in_tbs    = ""
  available_container_databases                    = ""
  available_cpus                                   = ""
  cloud_exadata_infrastructure_id                  = ""
  compute_model                                    = ""
  cpu_core_count                                   = ""
  cpu_core_count_per_node                          = ""
  cpu_percentage                                   = ""
  created_at                                       = ""
  data_storage_size_in_gbs                         = ""
  data_storage_size_in_tbs                         = ""
  db_servers                                       = []
  description                                      = ""
  display_name                                     = ""
  domain                                           = ""
  exadata_storage_in_tbs_lowest_scaled_value       = ""
  hostname                                         = ""
  id                                               = ""
  is_mtls_enabled_vm_cluster                       = ""
  license_model                                    = ""
  max_acds_lowest_scaled_value                     = ""
  memory_per_oracle_compute_unit_in_gbs            = ""
  memory_size_in_gbs                               = ""
  node_count                                       = ""
  non_provisionable_autonomous_container_databases = ""
  oci_resource_anchor_name                         = ""
  oci_url                                          = ""
  ocid                                             = ""
  odb_network_id                                   = ""
  odb_node_storage_size_in_gbs                     = ""
  percent_progress                                 = ""
  provisionable_autonomous_container_databases     = ""
  provisioned_autonomous_container_databases       = ""
  provisioned_cpus                                 = ""
  reclaimable_cpus                                 = ""
  region                                           = ""
  reserved_cpus                                    = ""
  scan_listener_port_non_tls                       = ""
  scan_listener_port_tls                           = ""
  shape                                            = ""
  status                                           = ""
  status_reason                                    = ""
  time_database_ssl_certificate_expires            = ""
  time_ords_certificate_expires                    = ""
  time_zone                                        = ""
  total_container_databases                        = ""
  
  maintenance_window {}
  
  tags = {}
}