resource "tencentcloud_dayu_ddos_policy_case" "tf-sample-dayu-ddos-policy-case" {
  app_type            = ""
  has_abroad          = ""
  has_initiate_tcp    = ""
  has_initiate_udp    = ""
  has_vpn             = ""
  max_tcp_package_len = ""
  max_udp_package_len = ""
  min_tcp_package_len = ""
  min_udp_package_len = ""
  name                = ""
  peer_tcp_port       = ""
  peer_udp_port       = ""
  resource_type       = ""
  tcp_end_port        = ""
  tcp_footprint       = ""
  tcp_start_port      = ""
  udp_end_port        = ""
  udp_footprint       = ""
  udp_start_port      = ""
}