resource "alicloud_esa_waiting_room_event" "tf-sample-esa-waiting-room-event" {
  custom_page_html               = ""
  description                    = ""
  disable_session_renewal_enable = ""
  end_time                       = ""
  json_response_enable           = ""
  language                       = ""
  new_users_per_minute           = ""
  pre_queue_enable               = ""
  pre_queue_start_time           = ""
  queuing_method                 = ""
  queuing_status_code            = ""
  random_pre_queue_enable        = ""
  session_duration               = ""
  site_id                        = ""
  start_time                     = ""
  status                         = ""
  total_active_users             = ""
  waiting_room_event_name        = ""
  waiting_room_id                = ""
  waiting_room_type              = ""
}