resource "alicloud_esa_cache_rule" "tf-sample-esa-cache-rule" {
  additional_cacheable_ports  = ""
  browser_cache_mode          = ""
  browser_cache_ttl           = ""
  bypass_cache                = ""
  cache_deception_armor       = ""
  cache_reserve_eligibility   = ""
  check_presence_cookie       = ""
  check_presence_header       = ""
  edge_cache_mode             = ""
  edge_cache_ttl              = ""
  edge_status_code_cache_ttl  = ""
  include_cookie              = ""
  include_header              = ""
  query_string                = ""
  query_string_mode           = ""
  rule                        = ""
  rule_enable                 = ""
  rule_name                   = ""
  sequence                    = 0
  serve_stale                 = ""
  site_id                     = ""
  site_version                = 0
  sort_query_string_for_cache = ""
  user_device_type            = ""
  user_geo                    = ""
  user_language               = ""
}