resource "aws_lightsail_database" "tf-sample-lightsail-database" {
  apply_immediately            = ""
  availability_zone            = ""
  backup_retention_enabled     = ""
  blueprint_id                 = ""
  bundle_id                    = ""
  ca_certificate_identifier    = ""
  cpu_count                    = ""
  created_at                   = ""
  disk_size                    = ""
  engine                       = ""
  engine_version               = ""
  final_snapshot_name          = ""
  id                           = ""
  master_database_name         = ""
  master_endpoint_address      = ""
  master_endpoint_port         = ""
  master_password              = ""
  master_username              = ""
  preferred_backup_window      = ""
  preferred_maintenance_window = ""
  publicly_accessible          = ""
  ram_size                     = ""
  region                       = ""
  relational_database_name     = ""
  secondary_availability_zone  = ""
  skip_final_snapshot          = ""
  support_code                 = ""
  
  tags = {}
}