resource "aws_dx_hosted_connection" "sample-dx-hosted-connection" {
  aws_device             = ""
  bandwidth              = ""
  connection_id          = ""
  connection_region      = ""
  has_logical_redundancy = ""
  id                     = ""
  jumbo_frame_capable    = ""
  lag_id                 = ""
  loa_issue_time         = ""
  location               = ""
  name                   = ""
  owner_account_id       = ""
  partner_name           = ""
  provider_name          = ""
  region                 = ""
  state                  = ""
  vlan                   = ""
}