resource "aws_lambda_permission" "tf-sample-lambda-permission" {
  action                 = ""
  event_source_token     = ""
  function_name          = ""
  function_url_auth_type = ""
  id                     = ""
  principal              = ""
  principal_org_id       = ""
  qualifier              = ""
  region                 = ""
  source_account         = ""
  source_arn             = ""
  statement_id           = ""
  statement_id_prefix    = ""
}