resource "aws_sns_topic_subscription" "sample-sns-topic-subscription" {
  confirmation_timeout_in_minutes = ""
  confirmation_was_authenticated  = ""
  delivery_policy                 = ""
  endpoint                        = ""
  endpoint_auto_confirms          = ""
  filter_policy                   = ""
  filter_policy_scope             = ""
  id                              = ""
  owner_id                        = ""
  pending_confirmation            = ""
  protocol                        = ""
  raw_message_delivery            = ""
  redrive_policy                  = ""
  region                          = ""
  replay_policy                   = ""
  subscription_role_arn           = ""
  topic_arn                       = ""
}