resource "aws_sns_topic" "tf-sample-sns-topic" {
  application_failure_feedback_role_arn    = ""
  application_success_feedback_role_arn    = ""
  application_success_feedback_sample_rate = ""
  archive_policy                           = ""
  beginning_archive_time                   = ""
  content_based_deduplication              = ""
  delivery_policy                          = ""
  display_name                             = ""
  fifo_throughput_scope                    = ""
  fifo_topic                               = ""
  firehose_failure_feedback_role_arn       = ""
  firehose_success_feedback_role_arn       = ""
  firehose_success_feedback_sample_rate    = ""
  http_failure_feedback_role_arn           = ""
  http_success_feedback_role_arn           = ""
  http_success_feedback_sample_rate        = ""
  id                                       = ""
  kms_master_key_id                        = ""
  lambda_failure_feedback_role_arn         = ""
  lambda_success_feedback_role_arn         = ""
  lambda_success_feedback_sample_rate      = ""
  name                                     = ""
  name_prefix                              = ""
  owner                                    = ""
  policy                                   = ""
  region                                   = ""
  signature_version                        = ""
  sqs_failure_feedback_role_arn            = ""
  sqs_success_feedback_role_arn            = ""
  sqs_success_feedback_sample_rate         = ""
  tracing_config                           = ""
  
  tags = {}
}