resource "alicloud_polardb_aicluster" "tf-sample-polardb-aicluster" {
  auto_renew             = ""
  auto_use_coupon        = false
  db_cluster_description = ""
  db_cluster_id          = ""
  db_node_class          = ""
  extension              = ""
  inference_engine       = ""
  kube_type              = ""
  model_name             = ""
  pay_type               = ""
  period                 = ""
  promotion_code         = ""
  region_id              = ""
  security_group_id      = ""
  used_time              = ""
  vpc_id                 = ""
  vswitch_id             = ""
  zone_id                = ""
}