resource "aws_neptune_cluster_instance" "sample-neptune-cluster-instance" {
  address                      = ""
  apply_immediately            = ""
  auto_minor_version_upgrade   = ""
  availability_zone            = ""
  cluster_identifier           = ""
  dbi_resource_id              = ""
  endpoint                     = ""
  engine                       = ""
  engine_version               = ""
  id                           = ""
  identifier                   = ""
  identifier_prefix            = ""
  instance_class               = ""
  kms_key_arn                  = ""
  neptune_parameter_group_name = ""
  neptune_subnet_group_name    = ""
  port                         = ""
  preferred_backup_window      = ""
  preferred_maintenance_window = ""
  promotion_tier               = ""
  publicly_accessible          = ""
  region                       = ""
  skip_final_snapshot          = ""
  storage_encrypted            = ""
  storage_type                 = ""
  writer                       = ""
  
  tags = {}
}