resource "aws_route" "tf-sample-route" {
  carrier_gateway_id          = ""
  core_network_arn            = ""
  destination_cidr_block      = ""
  destination_ipv6_cidr_block = ""
  destination_prefix_list_id  = ""
  egress_only_gateway_id      = ""
  gateway_id                  = ""
  id                          = ""
  instance_id                 = ""
  instance_owner_id           = ""
  local_gateway_id            = ""
  nat_gateway_id              = ""
  network_interface_id        = ""
  origin                      = ""
  region                      = ""
  route_table_id              = ""
  state                       = ""
  transit_gateway_id          = ""
  vpc_endpoint_id             = ""
  vpc_peering_connection_id   = ""
}