resource "aws_quicksight_account_subscription" "tf-sample-quicksight-account-subscription" {
  account_name                     = ""
  active_directory_name            = ""
  authentication_method            = ""
  aws_account_id                   = ""
  contact_number                   = ""
  directory_id                     = ""
  edition                          = ""
  email_address                    = ""
  first_name                       = ""
  iam_identity_center_instance_arn = ""
  last_name                        = ""
  notification_email               = ""
  realm                            = ""
  region                           = ""
}