resource "ibm_db2" "tf-sample-db2" {
  backup_location              = ""
  disk_encryption_instance_crn = ""
  disk_encryption_key_crn      = ""
  high_availability            = ""
  instance_type                = ""
  location                     = ""
  name                         = ""
  oracle_compatibility         = ""
  parameters                   = {}
  parameters_json              = ""
  plan                         = ""
  resource_group_id            = ""
  service                      = ""
  service_endpoints            = ""
  subscription_id              = ""
  
  allowlist_config {
    ip_addresses {
      address     = ""
      description = ""
    }
  }
  autoscale_config {
    auto_scaling_allow_plan_limit = false
    auto_scaling_enabled          = false
    auto_scaling_over_time_period = ""
    auto_scaling_pause_limit      = 0
    auto_scaling_threshold        = ""
  }
  custom_setting_config {
    db {
      act_sortmem_limit    = ""
      alt_collate          = ""
      app_ctl_heap_sz      = ""
      appgroup_mem_sz      = ""
      appl_memory          = ""
      applheapsz           = ""
      archretrydelay       = ""
      authn_cache_duration = ""
      auto_cg_stats        = ""
      auto_maint           = ""
      auto_reorg           = ""
      auto_reval           = ""
      auto_runstats        = ""
      auto_sampling        = ""
      auto_stats_views     = ""
      auto_stmt_stats      = ""
      auto_tbl_maint       = ""
      autorestart          = ""
      avg_appls            = ""
      catalogcache_sz      = ""
      chngpgs_thresh       = ""
      cur_commit           = ""
      database_memory      = ""
      db_collname          = ""
      db_mem_thresh        = ""
      dbheap               = ""
      ddl_compression_def  = ""
      ddl_constraint_def   = ""
      dec_arithmetic       = ""
      dec_to_char_fmt      = ""
      decflt_rounding      = ""
      dft_degree           = ""
      dft_extent_sz        = ""
      dft_loadrec_ses      = ""
      dft_mttb_types       = ""
      dft_prefetch_sz      = ""
      dft_queryopt         = ""
      dft_refresh_age      = ""
      dft_schemas_dcc      = ""
      dft_sqlmathwarn      = ""
      dft_table_org        = ""
      dlchktime            = ""
      enable_xmlchar       = ""
      extended_row_sz      = ""
      groupheap_ratio      = ""
      indexrec             = ""
      large_aggregation    = ""
      locklist             = ""
      locktimeout          = ""
      log_appl_info        = ""
      log_ddl_stmts        = ""
      log_disk_cap         = ""
      logindexbuild        = ""
      maxappls             = ""
      maxfilop             = ""
      maxlocks             = ""
      min_dec_div_3        = ""
      mon_act_metrics      = ""
      mon_deadlock         = ""
      mon_lck_msg_lvl      = ""
      mon_locktimeout      = ""
      mon_lockwait         = ""
      mon_lw_thresh        = ""
      mon_obj_metrics      = ""
      mon_pkglist_sz       = ""
      mon_req_metrics      = ""
      mon_rtn_data         = ""
      mon_rtn_execlist     = ""
      mon_uow_data         = ""
      mon_uow_execlist     = ""
      mon_uow_pkglist      = ""
      nchar_mapping        = ""
      num_freqvalues       = ""
      num_iocleaners       = ""
      num_ioservers        = ""
      num_log_span         = ""
      num_quantiles        = ""
      opt_buffpage         = ""
      opt_direct_wrkld     = ""
      opt_locklist         = ""
      opt_maxlocks         = ""
      opt_sortheap         = ""
      page_age_trgt_gcr    = ""
      page_age_trgt_mcr    = ""
      pckcachesz           = ""
      pl_stack_trace       = ""
      self_tuning_mem      = ""
      seqdetect            = ""
      sheapthres_shr       = ""
      softmax              = ""
      sortheap             = ""
      sql_ccflags          = ""
      stat_heap_sz         = ""
      stmt_conc            = ""
      stmtheap             = ""
      string_units         = ""
      systime_period_adj   = ""
      trackmod             = ""
      util_heap_sz         = ""
      wlm_admission_ctrl   = ""
      wlm_agent_load_trgt  = ""
      wlm_cpu_limit        = ""
      wlm_cpu_share_mode   = ""
      wlm_cpu_shares       = ""
    }
    dbm {
      comm_bandwidth      = ""
      cpuspeed            = ""
      dft_mon_bufpool     = ""
      dft_mon_lock        = ""
      dft_mon_sort        = ""
      dft_mon_stmt        = ""
      dft_mon_table       = ""
      dft_mon_timestamp   = ""
      dft_mon_uow         = ""
      diaglevel           = ""
      federated_async     = ""
      indexrec            = ""
      intra_parallel      = ""
      keepfenced          = ""
      max_connretries     = ""
      max_querydegree     = ""
      mon_heap_sz         = ""
      multipartsizemb     = ""
      notifylevel         = ""
      num_initagents      = ""
      num_initfenced      = ""
      num_poolagents      = ""
      resync_interval     = ""
      rqrioblk            = ""
      start_stop_time     = ""
      util_impact_lim     = ""
      wlm_disp_concur     = ""
      wlm_disp_cpu_shares = ""
      wlm_disp_min_util   = ""
      wlm_dispatcher      = ""
    }
    registry {
      db2_alternate_authz_behaviour    = ""
      db2_antijoin                     = ""
      db2_ats_enable                   = ""
      db2_bidi                         = ""
      db2_compopt                      = ""
      db2_deferred_prepare_semantics   = ""
      db2_evaluncommitted              = ""
      db2_extended_optimization        = ""
      db2_index_pctfree_default        = ""
      db2_inlist_to_nljn               = ""
      db2_lock_to_rb                   = ""
      db2_minimize_listprefetch        = ""
      db2_object_table_entries         = ""
      db2_opt_max_temp_size            = ""
      db2_optprofile                   = ""
      db2_optstats_log                 = ""
      db2_parallel_io                  = ""
      db2_reduced_optimization         = ""
      db2_selectivity                  = ""
      db2_skipdeleted                  = ""
      db2_skipinserted                 = ""
      db2_stmm                         = ""
      db2_sync_release_lock_attributes = ""
      db2_truncate_reusestorage        = ""
      db2_use_alternate_page_cleaning  = ""
      db2_view_reopt_values            = ""
      db2_wlm_settings                 = ""
      db2_workload                     = ""
    }
  }
  users_config {
    email    = ""
    iam      = false
    ibmid    = ""
    id       = ""
    locked   = ""
    name     = ""
    password = ""
    role     = ""
    
    authentication {
      method    = ""
      policy_id = ""
    }
  }
  
  tags = {}
}