resource "aws_workmail_user" "tf-sample-workmail-user" {
  city                            = ""
  company                         = ""
  country                         = ""
  department                      = ""
  display_name                    = ""
  email                           = ""
  first_name                      = ""
  hidden_from_global_address_list = false
  identity_provider_user_id       = ""
  initials                        = ""
  job_title                       = ""
  last_name                       = ""
  name                            = ""
  office                          = ""
  organization_id                 = ""
  password                        = ""
  region                          = ""
  street                          = ""
  telephone                       = ""
  user_role                       = ""
  zip_code                        = ""
}