resource "oci_stack_monitoring_monitored_resources_search" "tf-sample-stack-monitoring-monitored-resources-search" {
  compartment_id                        = ""
  external_id                           = ""
  host_name                             = ""
  host_name_contains                    = ""
  license                               = ""
  management_agent_id                   = ""
  name                                  = ""
  name_contains                         = ""
  resource_category                     = ""
  resource_time_zone                    = ""
  source_type                           = ""
  state                                 = ""
  time_created_greater_than_or_equal_to = ""
  time_created_less_than                = ""
  time_updated_greater_than_or_equal_to = ""
  time_updated_less_than                = ""
  type                                  = ""
}