resource "aws_elasticache_global_replication_group" "sample-elasticache-global-replication-group" {
  at_rest_encryption_enabled           = ""
  auth_token_enabled                   = ""
  automatic_failover_enabled           = ""
  cache_node_type                      = ""
  cluster_enabled                      = ""
  engine                               = ""
  engine_version                       = ""
  engine_version_actual                = ""
  global_node_groups                   = []
  global_replication_group_description = ""
  global_replication_group_id          = ""
  global_replication_group_id_suffix   = ""
  id                                   = ""
  num_node_groups                      = ""
  parameter_group_name                 = ""
  primary_replication_group_id         = ""
  region                               = ""
  transit_encryption_enabled           = ""
}