resource "aws_docdb_cluster_instance" "tf-sample-docdb-cluster-instance" {
  apply_immediately               = ""
  auto_minor_version_upgrade      = ""
  availability_zone               = ""
  ca_cert_identifier              = ""
  cluster_identifier              = ""
  copy_tags_to_snapshot           = ""
  db_subnet_group_name            = ""
  dbi_resource_id                 = ""
  enable_performance_insights     = ""
  endpoint                        = ""
  engine                          = ""
  engine_version                  = ""
  id                              = ""
  identifier                      = ""
  identifier_prefix               = ""
  instance_class                  = ""
  kms_key_id                      = ""
  performance_insights_kms_key_id = ""
  port                            = ""
  preferred_backup_window         = ""
  preferred_maintenance_window    = ""
  promotion_tier                  = ""
  publicly_accessible             = ""
  region                          = ""
  storage_encrypted               = ""
  writer                          = ""
  
  tags = {}
}