resource "azurerm_iothub_endpoint_cosmosdb_account" "tf-sample-iothub-endpoint-cosmosdb-account" {
  authentication_type    = ""
  container_name         = ""
  database_name          = ""
  endpoint_uri           = ""
  identity_id            = ""
  iothub_id              = ""
  name                   = ""
  partition_key_name     = ""
  partition_key_template = ""
  primary_key            = ""
  resource_group_name    = ""
  secondary_key          = ""
  subscription_id        = ""
}